server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

security:
  key:
    secret: ${}


appDescription: "Our API"
appVersion: "1.0.0"