server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: ${USER_DB}
    password: ${PASSWORD_DB}


  jpa:
    hibernate:
      ddl-auto: update

security:
  key:
    secret: ${SECRET_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

